"""Streamlit dashboard for newborn product market research.

Launch with:
    streamlit run app.py

The app expects `aggregated_products.csv` generated by `data_pipeline.py`.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

import altair as alt
import pandas as pd
import streamlit as st

AGGREGATED_PATH = Path("aggregated_products.csv")


def load_data(path: Path = AGGREGATED_PATH) -> pd.DataFrame:
    if not path.exists():
        st.error(f"Missing aggregated data at {path}. Run `python data_pipeline.py` first.")
        return pd.DataFrame()
    df = pd.read_csv(path)
    return df


def sidebar_filters(df: pd.DataFrame) -> pd.DataFrame:
    st.sidebar.header("Filters")
    categories = sorted(df["category"].dropna().unique())
    brands = sorted(df["brand"].dropna().unique())

    selected_categories = st.sidebar.multiselect("Category", categories, default=categories[:5])
    selected_brands = st.sidebar.multiselect("Brand", brands)

    min_price = float(df["min_price"].min()) if not df.empty else 0.0
    max_price = float(df["max_price"].max()) if not df.empty else 0.0
    price_range = st.sidebar.slider("Price range", min_price, max_price, (min_price, max_price))

    min_posts = st.sidebar.number_input("Minimum posts", min_value=0, value=0, step=1)
    min_likes = st.sidebar.number_input("Minimum total likes", min_value=0, value=0, step=10)

    filtered = df.copy()
    if selected_categories:
        filtered = filtered[filtered["category"].isin(selected_categories)]
    if selected_brands:
        filtered = filtered[filtered["brand"].isin(selected_brands)]
    filtered = filtered[(filtered["median_price"].between(price_range[0], price_range[1], inclusive="both"))]
    filtered = filtered[(filtered["num_posts"] >= min_posts) & (filtered["total_likes"] >= min_likes)]
    return filtered


def render_kpis(df: pd.DataFrame) -> None:
    st.subheader("High-level KPIs")
    total_products = df["product_id"].nunique()
    total_posts = int(df["num_posts"].sum())
    top_categories = (
        df.groupby("category")
        .agg(num_posts=("num_posts", "sum"))
        .sort_values("num_posts", ascending=False)
        .head(5)
    )
    col1, col2 = st.columns(2)
    col1.metric("Distinct products", f"{total_products}")
    col2.metric("Total posts", f"{total_posts}")
    st.markdown("**Top categories by posts**")
    st.dataframe(top_categories)


def render_table(df: pd.DataFrame) -> None:
    st.subheader("Top products")
    sort_option = st.selectbox("Sort by", ["num_posts", "total_likes", "median_price"], index=0)
    display_cols = [
        "product_name",
        "brand",
        "model",
        "category",
        "num_posts",
        "total_likes",
        "avg_likes",
        "median_price",
        "currency",
        "price_url_1",
        "price_url_2",
        "price_url_3",
    ]
    df_sorted = df.sort_values(sort_option, ascending=False)
    st.dataframe(df_sorted[display_cols])


def render_charts(df: pd.DataFrame) -> None:
    st.subheader("Charts")
    if df.empty:
        st.info("No data to display.")
        return

    top_categories = (
        df.groupby("category")
        .agg(num_posts=("num_posts", "sum"))
        .reset_index()
        .sort_values("num_posts", ascending=False)
        .head(10)
    )
    cat_chart = (
        alt.Chart(top_categories)
        .mark_bar()
        .encode(x=alt.X("num_posts:Q", title="Posts"), y=alt.Y("category:N", sort="-x"), tooltip=["category", "num_posts"])
    )
    st.altair_chart(cat_chart, use_container_width=True)

    selected_category = st.selectbox("Category for brand breakdown", sorted(df["category"].dropna().unique()))
    brand_df = df[df["category"] == selected_category]
    brand_counts = (
        brand_df.groupby("brand")
        .agg(num_posts=("num_posts", "sum"))
        .reset_index()
        .sort_values("num_posts", ascending=False)
        .head(10)
    )
    brand_chart = (
        alt.Chart(brand_counts)
        .mark_bar(color="#76A5AF")
        .encode(x=alt.X("num_posts:Q", title="Posts"), y=alt.Y("brand:N", sort="-x"), tooltip=["brand", "num_posts"])
    )
    st.altair_chart(brand_chart, use_container_width=True)

    if "recent_post_count" in df.columns:
        time_series = df[["product_name", "recent_post_count", "num_posts"]].copy()
        st.markdown("Recent activity (last 90 days counts per product)")
        st.dataframe(time_series.sort_values("recent_post_count", ascending=False).head(20))


def main() -> None:
    st.set_page_config(page_title="Newborn product insights", layout="wide")
    st.title("Newborn / Baby Product Market Research")
    st.write("This dashboard uses pre-exported social and e-commerce data. No live scraping is performed.")

    df = load_data()
    if df.empty:
        return

    filtered = sidebar_filters(df)
    render_kpis(filtered)
    render_table(filtered)
    render_charts(filtered)


if __name__ == "__main__":
    main()
